### ISSUE TITLE
Using cuser with an started project

### ISSUE THREAD

**Issue by lmorillas** [tmm/django-username-email#11]
When a project has data, the migration process raises a:
`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wagtaildocs.0001_initial is applied before its dependency cuser.0001_initial on database 'default'.
`
I'm reading that django docs don't recommend to change the user model once started the project.  Should it be possible with django-username-email?

**Comment by ataylor32** [comment]
`django-username-email` is the same as `django.contrib.auth` in this regard. Here is Django's documentation on how to handle this:

https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project
