### ISSUE TITLE
Form validation error on email field

### ISSUE THREAD

**Issue by cwazuidema** [tmm/django-username-email#17]
When validating the email address I kept running into errors when a new user wants to sign up.

I see this errors, because I use this print statement:
print(form.errors.as_json())

When I leave email empty I get this error (which is expected):
{"email": [{"message": "This field is required.", "code": "required"}]} 

When I enter a invalid email address I get this error (which is expected):
{"email": [{"message": "Enter a valid email address.", "code": "invalid"}]} 

When I enter a valid email address I get this error (which is NOT expected):
{"email": [{"message": "This field cannot be blank.", "code": "blank"}]} 

To fix this issue I edited the AbstractCUser class in cuser.models.py
I added blank=True, like this:

    email = models.EmailField(
        _('email address'),
        blank=True,
        unique=True,
        error_messages={
            'unique': _("A user with that email address already exists."),
        },
    )

Maybe I made a mistake somewhere else, not sure.
But this was my solution.

**Comment by ataylor32** [comment]
I haven't run into this. What does your form class look like?

**Comment by 67millwood** [comment]
I have struggled with exactly the same issue as above.  Same error message about the field being blank when it is not.

**Comment by ataylor32** [comment]
@67millwood What does your form class look like?

**Comment by cwazuidema** [comment]
My apologies for not replying quickly.

I'll include the used form at the bottom of this comment.

My current solution is to use the standard Django User and just use an email address as username (which Django accepts) and leave email blank.

Make sure to follow these steps so you can still add new fields to the User model:
https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project

Not sure if django-username-email is still needed now an email address is accepted as a username. But that's probably another discussion.
```
import django
from django import forms
from django.contrib.auth import (authenticate, get_user_model,
                                 password_validation)
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from cuser.models import CUser

UserModel = get_user_model()


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }```
    
    name = forms.CharField(
        label=_("Voornaam"),
        max_length=30,
        
    )
    
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(),
    )
    
    phone = forms.CharField(
        label=_("06-nummer"),
        max_length=20,
    )
    
    woonplaats = forms.CharField(
        label=_("Woonplaats"),
        max_length=20,
    )
    #
    # password1 = forms.CharField(
    #     label=_("Password"),
    #     strip=False,
    #     widget=forms.PasswordInput,
    #     help_text=password_validation.password_validators_help_text_html(),
    # )
    # password2 = forms.CharField(
    #     label=_("Password confirmation"),
    #     widget=forms.PasswordInput,
    #     strip=False,
    #     help_text=_("Enter the same password as before, for verification."),
    # )

    class Meta:
        model = CUser
        fields = []

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        print('start save usesr')
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            print('save the user')
            user.save()
        return user

**Comment by 67millwood** [comment]
did not create a custom User.  simply imported UserCreationForm from cuser.forms.  no modifications. creation of users via the Admin works perfectly (email field...no username as expected).  

![image](https://user-images.githubusercontent.com/19393233/57019271-00bba300-6bf4-11e9-949d-7051d25717f5.png)

error messages post filling in a normal email address and matching pwds...

![image](https://user-images.githubusercontent.com/19393233/57019355-382a4f80-6bf4-11e9-87cc-092b8cb3f471.png)

**Comment by ataylor32** [comment]
@cwazuidema @67millwood Thank you, I was able to reproduce and fix the bug. Version 2.2.4 has been released.

**Comment by 67millwood** [comment]
works like a charm.  great response on that one.  appreciate it.
