### ISSUE TITLE
Help with CUser: Reverse accessor clashing

### ISSUE THREAD

**Issue by effpi** [tmm/django-username-email#18]
I am using cuser as follows (having imported AbstractCUser):
class Utilisateur(AbstractCUser):
    telephone = models.CharField(max_length=10)
    doit_changer_mot_de_passe = models.BooleanField(default=True)
    a_accepte_CGU = models.BooleanField(default=False)
    est_administrateur = models.BooleanField(default=False)

Django returns the following errors:
core.Utilisateur.groups: (fields.E304) Reverse accessor for 'Utilisateur.groups' clashes with reverse accessor for 'CUser.groups'.
        HINT: Add or change a related_name argument to the definition for 'Utilisateur.groups' or 'CUser.groups'.
core.Utilisateur.user_permissions: (fields.E304) Reverse accessor for 'Utilisateur.user_permissions' clashes with reverse accessor for 'CUser.user_permissions'.
        HINT: Add or change a related_name argument to the definition for 'Utilisateur.user_permissions' or 'CUser.user_permissions'.
cuser.CUser.groups: (fields.E304) Reverse accessor for 'CUser.groups' clashes with reverse accessor for 'Utilisateur.groups'.
        HINT: Add or change a related_name argument to the definition for 'CUser.groups' or 'Utilisateur.groups'.
cuser.CUser.user_permissions: (fields.E304) Reverse accessor for 'CUser.user_permissions' clashes with reverse accessor for 'Utilisateur.user_permissions'.
        HINT: Add or change a related_name argument to the definition for 'CUser.user_permissions' or 'Utilisateur.user_permissions'.

What would you advise?

**Comment by ataylor32** [comment]
You need to have this in your settings:

```python
AUTH_USER_MODEL = 'core.Utilisateur'
```

**Comment by effpi** [comment]
This is much better! Thank you
