### ISSUE TITLE
Faulty `invalid_login` error message

### ISSUE THREAD

**Issue by ghost** [tmm/django-username-email#20]
The error message in cuser/templates/forms.py
```
'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
```
translates to : 
```
Please enter a correct email address and password. Note that both fields may be case-sensitive.
```

This is incorrect because email addresses are not case-sensitive. Only the password field may be case-sensitive.

**Comment by ghost** [comment]
Here's a suggested correction:
```
            "Please enter a correct %(username)s and password. Note the "
            "password may be case-sensitive."
```

**Comment by ataylor32** [comment]
Email addresses actually are case-sensitive (see [this link](https://stackoverflow.com/q/9807909/237244)). Django treats them as case-sensitive as well. The README already addressed this, but the issue you submitted prompted me to add a little to it, which I've done here:

https://github.com/tmm/django-username-email/commit/32f363e52a02e641449bee9ebf0053d1bbd54ae9
