### ISSUE TITLE
Avoid creating cuser_cuser_* tables when extend AbstractCUser.

### ISSUE THREAD

**Issue by softweave** [tmm/django-username-email#7]
I created a custom User model based on your django-username-email AbstractCUser class. A side effect is the creation of cuser_cuser_* tables even though they are never populated. I’m wondering how to avoid creating these tables.

Here is the contents of my users/model.py:
	from django.db import models
	from django.contrib.auth.models import Group as BaseGroup
	from cuser.models import AbstractCUser, CUserManager

	class User(AbstractCUser):
	    """
	    Password and email are required. Other fields are optional.
	    """
	    class Meta(AbstractCUser.Meta):
	        swappable = 'AUTH_USER_MODEL'

	class UserManager(CUserManager):
	    pass

	class Group(BaseGroup):
	    class Meta:
	        proxy = True

**Comment by ataylor32** [comment]
@softweave Thanks for reporting this! It's fixed now.

@tmm Will you please do a PyPI release at your earliest convenience? Thank you!

**Comment by tmm** [comment]
Thanks @ataylor32 for fixing!

@softweave latest is on PyPi
