### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by v-hunt** [tmm/django-username-email#8]
Hi, `migrate` command says that I have missing migration:
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

When I ran the command `./manage.py makemigrations cuser` it generated the new migration file for me with 
```python
migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
```

This looks odd because we have the same `email` field parameters in initial migration. Maybe it is due to that I use SQLite database for my small project. Anyway, I gonna to make PR with this odd missing migration.

Does anybody observe the same issue?

**Comment by ataylor32** [comment]
Thanks for reporting this! It was a Python 2 / 3 thing. This has been fixed by 8246395140c51208b727b3f9182f4d1f966efe2d
